### PR TITLE
Try to fix instrument point scale

### PR DESCRIPTION
**Pull request by evianzhow**
Attempt fix for https://github.com/giuse88/duka/issues/23
I'm Ruby programmer so I learned Python in 10 minutes, please don't laugh at me. :)
Additional commits are welcome.

### CODE REVIEW

**Comment by giuse88** [comment]
@EvianZhow Thanks for your help. I need a bit of time to review it and run the test. I will try to get it done this weekend. :)

**Comment by EvianZhow** [comment]
@giuse88 Hi, any progress on this? Maybe you should merge this into 2.1 release.

**Comment by giuse88** [comment]
@EvianZhow Thanks. I merged it.

**Comment by ipray4** [comment]
Does this program still work properly?? 
1. When i downloaded 1 year data, all ticks were in a single file.... not in the daily format....
2. and error occurs so that only a few data were downloaded... many days were missing....

**Pull request merged**
